name: ProLeagueEssencial
version: 1.4
main: me.freitas.proleague.ProLeagueEssencial
author: Freitas
description: Plugin oficial do servidor ProLeagueEssencial.
website: https://seusite.com

commands:
  # Comandos Gerais
  ping:
    description: Mostra o ping do jogador.
    usage: /ping [jogador]
    permission: proleague.ping

  horario:
    description: Mostra o horário do servidor.
    usage: /horario
    permission: proleague.horario

  suicide:
    description: Mata o próprio jogador.
    usage: /suicide
    permission: proleague.suicide

  motd:
    description: Exibe o MOTD do servidor.
    usage: /motd
    permission: proleague.motd

  whois:
    description: Mostra informações detalhadas de um jogador (IP, tempo online, localização).
    usage: /whois <jogador>
    permission: proleague.admin

  seen:
    description: Mostra a última vez que um jogador esteve online.
    usage: /seen <jogador>
    permission: proleague.utility

  # Sistema de Teleporte
  tp:
    description: Teleporta para um jogador.
    usage: /tp <jogador>
    permission: proleague.tp

  tpa:
    description: Solicita teleporte para um jogador.
    usage: /tpa <jogador>
    permission: proleague.tpa

  tpaccept:
    description: Aceita um pedido de teleporte.
    usage: /tpaccept
    permission: proleague.tpaccept

  tpdeny:
    description: Recusa um pedido de teleporte.
    usage: /tpdeny
    permission: proleague.tpdeny

  tphere:
    description: Teleporta um jogador até você.
    usage: /tphere <jogador>
    permission: proleague.tphere

  tpall:
    description: Teleporta todos os jogadores até você.
    usage: /tpall
    permission: proleague.tpall

  tptoggle:
    description: Ativa ou desativa pedidos de teleporte para si mesmo.
    usage: /tptoggle
    permission: proleague.tptoggle

  # Sistema de Warps e Spawn
  setspawn:
    description: Define o local de spawn global do servidor.
    usage: /setspawn
    permission: proleague.setspawn

  spawn:
    description: Teleporta para o spawn.
    usage: /spawn
    permission: proleague.spawn

  setwarp:
    description: Define um warp.
    usage: /setwarp <nome>
    permission: proleague.setwarp

  warp:
    description: Teleporta para um warp.
    usage: /warp <nome>
    permission: proleague.warp

  delwarp:
    description: Remove um warp.
    usage: /delwarp <nome>
    permission: proleague.delwarp

  warps:
    description: Lista todas as warps disponíveis.
    usage: /warps
    permission: proleague.warps

  # Comandos Administrativos
  reloadconfig:
    description: Recarrega a configuração do plugin.
    usage: /reloadconfig
    permission: proleague.admin

  vanish:
    description: Torna o jogador invisível.
    usage: /vanish
    permission: proleague.vanish

  freeze:
    description: Congela um jogador.
    usage: /freeze <jogador>
    permission: proleague.admin

  unfreeze:
    description: Descongela um jogador.
    usage: /unfreeze <jogador>
    permission: proleague.admin

  clearchat:
    description: Limpa o chat para todos os jogadores.
    usage: /clearchat
    permission: proleague.admin

  # Sistema de Itens e Inventário
  encantar:
    description: Encanta o item que você está segurando.
    usage: /encantar <encantamento> <nível>
    permission: proleague.encantar

  anvil:
    description: Abre uma bigorna virtual.
    usage: /anvil
    permission: proleague.anvil

  workbench:
    description: Abre uma bancada de trabalho virtual.
    usage: /workbench
    permission: proleague.workbench

  enderchest:
    description: Abre o baú do Ender.
    usage: /enderchest [jogador]
    permission: proleague.enderchest

  invsee:
    description: Permite visualizar e editar o inventário de um jogador.
    usage: /invsee <jogador>
    permission: proleague.invsee

  clearinventory:
    description: Limpa o inventário de um jogador.
    usage: /clearinventory [jogador]
    permission: proleague.clearinventory

  reparar:
    description: Repara o item na mão ou todo o inventário de um jogador.
    usage: /reparar [mao|tudo] [jogador]
    permission: proleague.reparar

  hat:
    description: Coloca ou remove um item na cabeça.
    usage: /hat
    permission: proleague.hat

  # Clima e Tempo
  day:
    description: Define o horário do mundo como dia.
    usage: /day
    permission: proleague.time

  night:
    description: Define o horário do mundo como noite.
    usage: /night
    permission: proleague.time

  rain:
    description: Faz chover no servidor.
    usage: /rain
    permission: proleague.admin

  sun:
    description: Define o clima como ensolarado.
    usage: /sun
    permission: proleague.admin

  thunder:
    description: Inicia uma tempestade.
    usage: /thunder
    permission: proleague.admin

  ptime:
    description: Define o tempo pessoal do jogador.
    usage: /ptime <dia|noite|reset>
    permission: proleague.time

  pweather:
    description: Define o clima pessoal do jogador.
    usage: /pweather <sol|chuva|reset>
    permission: proleague.weather

  # Outros Comandos
  god:
    description: Ativa ou desativa o modo deus.
    usage: /god [jogador]
    permission: proleague.god

  fly:
    description: Ativa ou desativa o voo do jogador.
    usage: /fly [jogador]
    permission: proleague.fly

  heal:
    description: Cura completamente o jogador.
    usage: /heal [jogador]
    permission: proleague.heal

  speed:
    description: Define a velocidade do jogador.
    usage: /speed <valor> [jogador]
    permission: proleague.speed

  sudo:
    description: Executa um comando como outro jogador.
    usage: /sudo <jogador> <comando>
    permission: proleague.sudo

  feed:
    description: Restaura a fome do jogador.
    usage: /feed [jogador]
    permission: proleague.feed

  broadcast:
    description: Envia uma mensagem global para todos os jogadores.
    usage: /broadcast <mensagem>
    permission: proleague.broadcast

  keepinventory:
    description: Mantém o inventário do jogador ao morrer.
    usage: /keepinventory [on|off]
    permission: proleague.keepinventory

  keepxp:
    description: Mantém a experiência do jogador ao morrer.
    usage: /keepxp [on|off]
    permission: proleague.keepxp

  realname:
    description: Exibe o nome real de um jogador caso esteja usando nick.
    usage: /realname <jogador>
    permission: proleague.nick