name: ProLeagueEssencial
version: 1.3
main: me.freitas.proleague.ProLeagueEssencial
author: Freitas
description: Plugin oficial do servidor ProLeagueEssencial.
website: https://seusite.com

commands:
  # Comandos Gerais
  ping:
    description: Mostra o ping do jogador.
    usage: /ping [jogador]
    permission: proleague.ping

  horario:
    description: Mostra o horário do servidor.
    usage: /horario
    permission: proleague.horario

  suicide:
    description: Mata o próprio jogador.
    usage: /suicide
    permission: proleague.suicide

  spawn:
    description: Teleporta para o spawn.
    usage: /spawn
    permission: proleague.spawn

  motd:
    description: Exibe o MOTD do servidor.
    usage: /motd
    permission: proleague.motd

  # Sistema de Homes
  home:
    description: Teleporta para uma home.
    usage: /home <nome>
    permission: proleague.home

  sethome:
    description: Define uma home com um nome específico.
    usage: /sethome <nome>
    permission: proleague.sethome

  delhome:
    description: Remove uma home específica.
    usage: /delhome <nome>
    permission: proleague.delhome

  listhomes:
    description: Lista todas as homes do jogador.
    usage: /listhomes
    permission: proleague.listhomes

  # Sistema de Warps
  warp:
    description: Teleporta para um warp.
    usage: /warp <nome>
    permission: proleague.warp

  setwarp:
    description: Define um warp.
    usage: /setwarp <nome>
    permission: proleague.setwarp

  delwarp:
    description: Remove um warp.
    usage: /delwarp <nome>
    permission: proleague.delwarp

  warps:
    description: Lista todas as warps disponíveis.
    usage: /warps
    permission: proleague.warps

  # Sistema de Teleporte
  tp:
    description: Teleporta para um jogador.
    usage: /tp <jogador>
    permission: proleague.tp

  tpa:
    description: Solicita teleporte para um jogador.
    usage: /tpa <jogador>
    permission: proleague.tpa

  tpaccept:
    description: Aceita um pedido de teleporte.
    usage: /tpaccept
    permission: proleague.tpaccept

  tpdeny:
    description: Recusa um pedido de teleporte.
    usage: /tpdeny
    permission: proleague.tpdeny

  # Comandos de Modos de Jogo
  gm:
    description: Altera o modo de jogo do jogador.
    usage: /gm <0|1|2|3> [jogador]
    permission: proleague.gm

  # Comandos de Tempo
  day:
    description: Define o horário do mundo como dia.
    usage: /day
    permission: proleague.time

  night:
    description: Define o horário do mundo como noite.
    usage: /night
    permission: proleague.time

  # Comandos Utilitários
  fly:
    description: Ativa ou desativa o voo do jogador.
    usage: /fly [jogador]
    permission: proleague.fly

  god:
    description: Ativa ou desativa o modo deus.
    usage: /god [jogador]
    permission: proleague.god

  heal:
    description: Cura completamente o jogador.
    usage: /heal [jogador]
    permission: proleague.heal

  speed:
    description: Define a velocidade do jogador.
    usage: /speed <valor> [jogador]
    permission: proleague.speed

  sudo:
    description: Executa um comando como outro jogador.
    usage: /sudo <jogador> <comando>
    permission: proleague.sudo

  info:
    description: Mostra todas as informações de um jogador.
    usage: /info <jogador>
    permission: proleague.admin

  encantar:
    description: Encanta o item que você está segurando.
    usage: /encantar <encantamento> <nível>
    permission: proleague.encantar

  back:
    description: Retorna para a última localização antes de morrer ou teleportar.
    usage: /back
    permission: proleague.back

  # Comandos Administrativos
  reloadconfig:
    description: Recarrega a configuração do plugin.
    usage: /reloadconfig
    permission: proleague.admin

  vanish:
    description: Torna o jogador invisível.
    usage: /vanish
    permission: proleague.vanish

  kick:
    description: Expulsa um jogador do servidor.
    usage: /kick <jogador> [motivo]
    permission: proleague.admin

  ban:
    description: Bane um jogador do servidor.
    usage: /ban <jogador> [motivo]
    permission: proleague.admin

  unban:
    description: Remove o banimento de um jogador.
    usage: /unban <jogador>
    permission: proleague.admin

  feed:
    description: Restaura a fome do jogador.
    usage: /feed [jogador]
    permission: proleague.feed

  anvil:
    description: Abre uma bigorna virtual.
    usage: /anvil
    permission: proleague.anvil

  enderchest:
    description: Abre o baú do Ender.
    usage: /enderchest [jogador]
    permission: proleague.enderchest

  reparar:
    description: Repara o item na mão ou todo o inventário de um jogador.
    usage: /reparar [mao|tudo] [jogador]
    permission: proleague.reparar

  broadcast:
    description: Envia uma mensagem global para todos os jogadores.
    usage: /broadcast <mensagem>
    permission: proleague.broadcast

  setspawn:
    description: Define o local de spawn global do servidor.
    usage: /setspawn
    permission: proleague.setspawn

  ext:
    description: Apaga o fogo do jogador.
    usage: /ext
    permission: proleague.ext

  freeze:
    description: Congela um jogador.
    usage: /freeze <jogador>
    permission: proleague.admin

  unfreeze:
    description: Descongela um jogador.
    usage: /unfreeze <jogador>
    permission: proleague.admin

  clearchat:
    description: Limpa o chat para todos os jogadores.
    usage: /clearchat
    permission: proleague.admin

  rain:
    description: Faz chover no servidor.
    usage: /rain
    permission: proleague.admin

  sun:
    description: Define o clima como ensolarado.
    usage: /sun
    permission: proleague.admin

  thunder:
    description: Inicia uma tempestade.
    usage: /thunder
    permission: proleague.admin

  warn:
    description: Envia um aviso para um jogador.
    usage: /warn <jogador> <motivo>
    permission: proleague.admin

  history:
    description: Mostra o histórico de punições de um jogador.
    usage: /history <jogador>
    permission: proleague.admin

  mute:
    description: Muta um jogador.
    usage: /mute <jogador>
    permission: proleague.admin

  unmute:
    description: Desmuta um jogador.
    usage: /unmute <jogador>
    permission: proleague.admin

  banip:
    description: Bane o IP de um jogador.
    usage: /banip <jogador>
    permission: proleague.admin

  unbanip:
    description: Desbane um IP.
    usage: /unbanip <ip>
    permission: proleague.admin

  tphere:
    description: Teleporta um jogador até você.
    usage: /tphere <jogador>
    permission: proleague.tphere

  nick:
    description: Define um apelido personalizado.
    usage: /nick <novo_nome>
    permission: proleague.nick

  realname:
    description: Mostra o nome real de um jogador com apelido.
    usage: /realname <jogador>
    permission: proleague.realname

  invsee:
    description: Abre o inventário de outro jogador.
    usage: /invsee <jogador>
    permission: proleague.invsee

  hat:
    description: Coloca ou remove um item na cabeça.
    usage: /hat
    permission: proleague.hat