name: ProLeagueEssencial
version: 1.4
main: me.freitas.proleague.ProLeagueEssencial
author: Freitas
description: Plugin oficial do servidor ProLeagueEssencial.
website: https://seusite.com

commands:
  ping:
    description: Mostra o ping do jogador.
    usage: /ping [jogador]
    permission: proleague.ping

  horario:
    description: Mostra o horário do servidor.
    usage: /horario
    permission: proleague.horario

  suicide:
    description: Mata o próprio jogador.
    usage: /suicide
    permission: proleague.suicide

  motd:
    description: Exibe o MOTD do servidor.
    usage: /motd
    permission: proleague.motd

  whois:
    description: Mostra informações detalhadas de um jogador.
    usage: /whois <jogador>
    permission: proleague.admin

  seen:
    description: Mostra a última vez que um jogador esteve online.
    usage: /seen <jogador>
    permission: proleague.admin

  tp:
    description: Teleporta para um jogador.
    usage: /tp <jogador>
    permission: proleague.tp

  tpa:
    description: Solicita teleporte para um jogador.
    usage: /tpa <jogador>
    permission: proleague.tpa

  tpaccept:
    description: Aceita um pedido de teleporte.
    usage: /tpaccept
    permission: proleague.tpaccept

  tpdeny:
    description: Recusa um pedido de teleporte.
    usage: /tpdeny
    permission: proleague.tpdeny

  tphere:
    description: Teleporta um jogador até você.
    usage: /tphere <jogador>
    permission: proleague.tphere

  tpall:
    description: Teleporta todos os jogadores até você.
    usage: /tpall
    permission: proleague.tpall

  setspawn:
    description: Define o spawn global do servidor.
    usage: /setspawn
    permission: proleague.setspawn

  spawn:
    description: Teleporta para o spawn global.
    usage: /spawn
    permission: proleague.spawn

  sethome:
    description: Define um ponto de home.
    usage: /sethome [nome]
    permission: proleague.home

  home:
    description: Teleporta para uma home.
    usage: /home [nome]
    permission: proleague.home

  delhome:
    description: Remove uma home.
    usage: /delhome [nome]
    permission: proleague.home

  listhomes:
    description: Lista todas as homes do jogador.
    usage: /listhomes
    permission: proleague.listhomes

  back:
    description: Retorna ao local anterior.
    usage: /back
    permission: proleague.back

  setwarp:
    description: Define um warp.
    usage: /setwarp <nome>
    permission: proleague.setwarp

  warp:
    description: Teleporta para um warp.
    usage: /warp <nome>
    permission: proleague.warp

  delwarp:
    description: Remove um warp.
    usage: /delwarp <nome>
    permission: proleague.delwarp

  warps:
    description: Lista todos os warps.
    usage: /warps
    permission: proleague.warp

  reloadconfig:
    description: Recarrega a configuração do plugin.
    usage: /reloadconfig
    permission: proleague.admin

  vanish:
    description: Torna o jogador invisível.
    usage: /vanish
    permission: proleague.vanish

  freeze:
    description: Congela um jogador.
    usage: /freeze <jogador>
    permission: proleague.admin

  unfreeze:
    description: Descongela um jogador.
    usage: /unfreeze <jogador>
    permission: proleague.admin

  day:
    description: Define o tempo como dia.
    usage: /day
    permission: proleague.admin

  night:
    description: Define o tempo como noite.
    usage: /night
    permission: proleague.admin

  rain:
    description: Faz chover.
    usage: /rain
    permission: proleague.admin

  sun:
    description: Define o tempo como ensolarado.
    usage: /sun
    permission: proleague.admin

  thunder:
    description: Inicia uma tempestade.
    usage: /thunder
    permission: proleague.admin

  gm:
    description: Altera o modo de jogo.
    usage: /gm <0|1|2>
    permission: proleague.gm

  fly:
    description: Ativa ou desativa o modo de voo.
    usage: /fly [jogador]
    permission: proleague.fly

  god:
    description: Ativa ou desativa o modo god.
    usage: /god [jogador]
    permission: proleague.god

  heal:
    description: Cura o jogador.
    usage: /heal [jogador]
    permission: proleague.heal

  speed:
    description: Ajusta a velocidade do jogador.
    usage: /speed <valor> [jogador]
    permission: proleague.speed

  sudo:
    description: Força um jogador a executar um comando.
    usage: /sudo <jogador> <comando>
    permission: proleague.sudo

  info:
    description: Exibe informações do jogador.
    usage: /info [jogador]
    permission: proleague.info

  hat:
    description: Coloca o item na cabeça do jogador.
    usage: /hat
    permission: proleague.hat

  feed:
    description: Restaura a fome do jogador.
    usage: /feed [jogador]
    permission: proleague.feed

  anvil:
    description: Abre a interface da bigorna.
    usage: /anvil
    permission: proleague.anvil

  enderchest:
    description: Abre o enderchest do jogador.
    usage: /enderchest [jogador]
    permission: proleague.enderchest

  reparar:
    description: Repara o item na mão ou no inventário.
    usage: /reparar [mao|tudo] [jogador]
    permission: proleague.reparar

  broadcast:
    description: Envia uma mensagem global.
    usage: /broadcast <mensagem>
    permission: proleague.broadcast

  encantar:
    description: Encanta o item em mão.
    usage: /encantar <encantamento> <nível>
    permission: proleague.encantar

  ext:
    description: Executa uma ação extra.
    usage: /ext <parâmetros>
    permission: proleague.ext

  clearchat:
    description: Limpa o chat.
    usage: /clearchat
    permission: proleague.clearchat

  invsee:
    description: Visualiza o inventário de um jogador.
    usage: /invsee <jogador>
    permission: proleague.invsee

  clearinventory:
    description: Limpa o inventário de um jogador.
    usage: /clearinventory [jogador]
    permission: proleague.clearinventory

  keepxp:
    description: Ativa ou desativa a manutenção de XP na morte.
    usage: /keepxp [on|off]
    permission: proleague.keepxp

  keepinventory:
    description: Ativa ou desativa a manutenção do inventário na morte.
    usage: /keepinventory [on|off]
    permission: proleague.keepinventory

  deathpoint:
    description: Exibe o ponto de morte do jogador.
    usage: /deathpoint
    permission: proleague.deathpoint

  nick:
    description: Define ou remove o nick de um jogador.
    usage: /nick [jogador] [novo nick]
    permission: proleague.nick

  realname:
    description: Exibe o nome real do jogador.
    usage: /realname <jogador>
    permission: proleague.realname

  kit:
    description: Gerencia os kits (criar, deletar, dar, pegar ou abrir GUI).
    usage: /kit [criar|deletar|dar|gui|listar] <nome> [argumentos]
    aliases: [kits]

permissions:
  proleague.admin:
    description: Permissões de administradores do ProLeagueEssencial.
    default: op
    children:
      proleague.tp: true
      proleague.tphere: true
      proleague.tpall: true
      proleague.setspawn: true
      proleague.setwarp: true
      proleague.delwarp: true
      proleague.gm: true
      proleague.fly: true
      proleague.god: true
      proleague.heal: true
      proleague.speed: true
      proleague.sudo: true
      proleague.info: true
      proleague.hat: true
      proleague.feed: true
      proleague.anvil: true
      proleague.enderchest: true
      proleague.reparar: true
      proleague.broadcast: true
      proleague.encantar: true
      proleague.ext: true
      proleague.clearchat: true
      proleague.invsee: true
      proleague.clearinventory: true
      proleague.keepxp: true
      proleague.keepinventory: true
      proleague.deathpoint: true
      proleague.nick: true
      proleague.realname: true

  proleague.player:
    description: Permissões básicas para jogadores comuns.
    default: true
    children:
      proleague.spawn: true
      proleague.warp: true
      proleague.ping: true
      proleague.suicide: true
      proleague.home: true
      proleague.back: true
      proleague.tpa: true
      proleague.tpaccept: true
      proleague.tpdeny: true
      proleague.listhomes: true